from .auth import auth_bp
from .accounts import account_bp
from .projects import project_bp
from .activities import activity_bp
from .client_portal import portal_bp
from .queries import queries_bp
from .dashboard import dash_bp
from .meeting_requests import meeting_req_bp
from .notifications import notif_bp
from .leads import leads_bp
from .opportunities import opp_bp
from .contacts import contact_bp
from .enterprise import enterprise_bp
from .admin import admin_bp
from .search import search_bp
from .teams import team_bp
from .myworkspace import me_bp
from .employee import employee_bp
from .pm import pm_bp
from .vulnerabilities import vuln_bp
from .attendance import attendance_bp
from .backlog import backlog_bp
from .clients import client_bp
